# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://mkrech.github.io',
                'git_url': 'https://github.com/mkrech/nbdev_cards',
                'lib_path': 'nbdev_cards'},
  'syms': { 'nbdev_cards.cards': { 'nbdev_cards.cards.Card': ('card.html#card', 'nbdev_cards/cards.py'),
                                   'nbdev_cards.cards.Card.__eq__': ('card.html#card.__eq__', 'nbdev_cards/cards.py'),
                                   'nbdev_cards.cards.Card.__gt__': ('card.html#card.__gt__', 'nbdev_cards/cards.py'),
                                   'nbdev_cards.cards.Card.__init__': ('card.html#card.__init__', 'nbdev_cards/cards.py'),
                                   'nbdev_cards.cards.Card.__lt__': ('card.html#card.__lt__', 'nbdev_cards/cards.py'),
                                   'nbdev_cards.cards.Card.__str__': ('card.html#card.__str__', 'nbdev_cards/cards.py')},
            'nbdev_cards.core': {'nbdev_cards.core.foo': ('deck.html#foo', 'nbdev_cards/core.py')}}}
