# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 3
suits = ['♠','♥', '♦', '♣']
ranks =[None ,"A"] + [str(i) for i in range(2,11)] + ['J','Q','K']


# %% ../nbs/00_card.ipynb 11
class Card:
    "A playing card"
    def __init__(
            self, 
            suit:int, # An index into `suits`
            rank:int): # An index into `ranks`
          self.suit, self.rank = suit, rank
    def __str__(self): return f'{ranks[self.rank]}{suits[self.suit]}'
    __repr__ = __str__

