# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 2
from .card import *
from fastcore.utils import *

# %% ../nbs/01_deck.ipynb 4
class Deck:
    """A deck of 52 cards, not included jokers."""
    def __init__(self): self.cards=[Card(s,r) for s in range(4) for r in range(1, 14)]
    def __len__(self): return len(self.cards) # len(deck)
    def __str__(self): return '; '.join([str(c) for c in self.cards]) 
    def __contains__(self, card): return card in self.cards # Card(1, 1) in deck
    __repr__=__str__

